# Generated by Django 3.2.3 on 2021-06-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Quantidade'),
        ),
    ]
