# Generated by Django 3.2.3 on 2021-06-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_produto_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Código',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Preço',
        ),
    ]
