# Generated by Django 3.2.3 on 2021-06-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210602_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default='', max_length=30, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço'),
        ),
    ]
